//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceSystem.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MailResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MailResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InvoiceSystem.Resources.MailResources", typeof(MailResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;![CDATA[&lt;html&gt;&lt;body&gt;&lt;h2&gt;Përshëndetje {CustomerName},&lt;/h2&gt;&lt;p&gt;Ju sapo keni marrë një faturë të re:&lt;/p&gt;&lt;ul&gt;&lt;li&gt;Numri i Faturës: {InvoiceId}&lt;/li&gt;&lt;li&gt;Data e Faturës: {InvoiceDate}&lt;/li&gt;&lt;li&gt;Shuma Totale: {InvoiceAmount} LEKË&lt;/li&gt;&lt;li&gt;Zbritje: {InvoiceDiscount}&lt;/li&gt;&lt;li&gt;Afati i Pagesës: {InvoiceDueDate}&lt;/li&gt;&lt;/ul&gt;&lt;p&gt;Faleminderit,&lt;br/&gt;Sistemi i Faturimit&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;]]&gt;.
        /// </summary>
        public static string InvoiceMailBody {
            get {
                return ResourceManager.GetString("InvoiceMailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ildaashehu74@gmail.com.
        /// </summary>
        public static string InvoiceMailSender {
            get {
                return ResourceManager.GetString("InvoiceMailSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura #{InvoiceId} – {InvoiceDate}.
        /// </summary>
        public static string InvoiceMailSubject {
            get {
                return ResourceManager.GetString("InvoiceMailSubject", resourceCulture);
            }
        }
    }
}
